//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DziennikOcen
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRZEDMIOT
    {
        public PRZEDMIOT()
        {
            this.PROJEKT = new HashSet<PROJEKT>();
            this.przedmioty = new HashSet<przedmioty>();
        }
    
        public int id_PRZEDMIOTU { get; set; }
        public string nazwa_przedmiotu { get; set; }
        public string opis_przedmiotu { get; set; }
        public Nullable<int> ECTS { get; set; }
    
        public virtual ICollection<PROJEKT> PROJEKT { get; set; }
        public virtual ICollection<przedmioty> przedmioty { get; set; }
    }
}
