//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DziennikOcenWeb2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DziennikOcenEntities : DbContext
    {
        public DziennikOcenEntities()
            : base("name=DziennikOcenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GRUPA> GRUPA { get; set; }
        public DbSet<PROJEKT> PROJEKT { get; set; }
        public DbSet<projekty> projekty { get; set; }
        public DbSet<PROWADZĄCY> PROWADZĄCY { get; set; }
        public DbSet<PRZEDMIOT> PRZEDMIOT { get; set; }
        public DbSet<przedmioty> przedmioty { get; set; }
        public DbSet<STUDENT> STUDENT { get; set; }
    }
}
