//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DziennikOcenWeb2
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPA
    {
        public GRUPA()
        {
            this.STUDENT = new HashSet<STUDENT>();
        }
    
        public int id_GRUPY { get; set; }
        public string nazwa_grupy { get; set; }
    
        public virtual ICollection<STUDENT> STUDENT { get; set; }
    }
}
