//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DziennikOcenWeb2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJEKT
    {
        public PROJEKT()
        {
            this.projekty = new HashSet<projekty>();
        }
    
        public int id_PROJEKTU { get; set; }
        public Nullable<int> id_PRZEDMIOTU { get; set; }
        public string nazwa_projektu { get; set; }
        public string opis_projektu { get; set; }
    
        public virtual PRZEDMIOT PRZEDMIOT { get; set; }
        public virtual ICollection<projekty> projekty { get; set; }
    }
}
