//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DziennikOcenWeb2
{
    using System;
    using System.Collections.Generic;
    
    public partial class przedmioty
    {
        public int id_STUDENTA { get; set; }
        public int id_PROWADZĄCEGO { get; set; }
        public int id_PRZEDMIOTU { get; set; }
        public Nullable<int> ocena_przedmiotu { get; set; }
        public Nullable<System.DateTime> data_zaliczenia_przedmiotu { get; set; }
        public string uwagi_przedmiotu { get; set; }
    
        public virtual PROWADZĄCY PROWADZĄCY { get; set; }
        public virtual PRZEDMIOT PRZEDMIOT { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
